title: Sébastien Duval
subtitle: Doctor in Cryptography
subtitle_fr: Docteur en Cryptographie
description: "I am currently a post-doctoral researcher in France at the University of Versailles in the Crypto team. I previously worked at UCLouvain in Belgium in the Crypto group. I obtained my PhD from Sorbonne University in 2018, which I undertook at Inria as part of project-team SECRET under the supervision of Anne CANTEAUT and Gaëtan LEURENT. 
The goal of my research is to merge the advances of symmetric-key cryptographie and of side-channel attacks resistance, in order to build cryptographic solutions resisting both classical attacks and attacks on the implementations, with a cost fit for the Internet of Things. 
My interests include (1) the design of symmetric-key algorithms (ciphers, MACs and authenticated encryption schemes), (2) their statistical analysis, (3) the implementation of components or full cryptographic primitives (S-boxes, diffusion matrices, arithmetic over Boolean finite fields) in terms of logic circuits and onto implementations on micro-controllers and (4) counter-measures against side-channel and fault attacks. My main research subject is the combination of all these fields. 
I taught for three years at Sorbonne University, in campus Pierre-et-Marie-Curie, for bachelor students in computer science, then I taught master students in electricity at UCLouvain for two years, and I currently teach bachelor students in computer science at University of Versailles.

Je suis actuellement en post-doctorat à l'Université de Versailles dans l'équipe Crypto. Je travaillais précédemment à l'UCLouvain en Belgique dans l'équipe Crypto. J'ai obtenu mon doctorat de Sorbonne Université en 2018, effectué à Inria au sein de l'équipe-projet SECRET sous la supervision d' Anne CANTEAUT et de Gaëtan LEURENT. 
L'objectif de mes recherche est de concilier les avancées de la cryptographie symétrique et de la résistance aux attaques par canaux auxiliaires, afin de construire des solutions cryptographiques résistantes aux attaques classiques et aux attaques sur les implémentations, à un coût adapté à l'internet des objets. 
Mes centres d'intérêts comprennent
la conception d'algorithmes de cryptographie symétrique (chiffrements, MACs et chiffrements authentifiés),
leur analyse statistique,
l'implémentation de composants ou de primitives cryptographiques complètes (boîtes-S, matrices de diffusion, arithmétique dans les corps finis Booléens) en termes de circuits logiques et jusqu'à des implémentations sur micro-contrôleurs,
les contre-mesures aux attaques par canaux auxiliaires et attaques par fautes.
Mon sujet de recherche principal est la combinaison de tous ces domaines. 
J'ai enseigné pendant trois ans à Sorbonne Université, au campus Pierre-et-Marie-Curie, à des étudiants de licence d'informatique, puis pendant deux ans à des étudiants de master d'électricité à l'UCLouvain, et actuellement à des étudiants de licence d'informatique à l'Université de Versailles."
typewrite-text: Doctor in Cryptography
logo: avatar.jpeg
  

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Home
      text_fr: Accueil
      url: /
    - text: Research
      text_fr: Recherche
      url: /research
    - text: Teaching
      text_fr: Enseignement
      url: /teaching

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: avatar.jpeg
author: Sébastien Duval
author_bio: 'I am currently a post-doctoral researcher in France at the <a href="http://www.uvsq.fr/welcome-to-uvsq-406434.kjsp?RH=VF&RF=EN" target="_blank">University of Versailles</a>
      in the
      <a href="https://lmv.math.cnrs.fr/en/teams/cryptology-and-information-security-crypto/" target="_blank">Crypto team</a>.
      I previously worked at 
      <a href="https://uclouvain.be/en/index.html" target="_blank">UCLouvain</a>
      in Belgium in the 
      <a href="https://www-crypto.elen.ucl.ac.be/crypto/default/home" target="_blank">Crypto group</a>.
      I obtained my PhD from 
      <a href="https://www.sorbonne-universite.fr/en" target="_blank">Sorbonne University</a>
      in 2018, which I undertook at 
      <a href="https://www.inria.fr/en/" target="_blank">Inria</a>
      as part of project-team 
      <a href="https://www.rocq.inria.fr/secret/index.php?lg=en" target="_blank">SECRET</a>
      under the supervision of 
      <a href="https://who.rocq.inria.fr/Anne.Canteaut" target="_blank">Anne CANTEAUT</a>
      and 
      <a href="https://who.rocq.inria.fr/Gaetan.Leurent" target="_blank">Gaëtan LEURENT</a>.
      <br>
      The goal of my research is to merge the advances of symmetric-key cryptographie and of side-channel attacks resistance, in order to build cryptographic solutions resisting both classical attacks and attacks on the implementations, with a cost fit for the Internet of Things.
      <br>
      My interests include (1) the design of symmetric-key algorithms (ciphers, MACs and authenticated encryption schemes), (2) their statistical analysis, (3) the implementation of components or full cryptographic primitives (S-boxes, diffusion matrices, arithmetic over Boolean finite fields) in terms of logic circuits and onto implementations on micro-controllers and (4) counter-measures against side-channel and fault attacks. My main research subject is the combination of all these fields.
      <br>
      <p>
      I taught for three years at Sorbonne University, in campus Pierre-et-Marie-Curie, for bachelor students in computer science, then I taught master students in electricity at UCLouvain for two years, and I currently teach bachelor students in computer science at University of Versailles.
      </p>'
author_bio_fr: "Je suis actuellement en post-doctorat à <a href='http://www.uvsq.fr/' target='_blank'>l'Université de Versailles</a>
      dans l'équipe
      <a href='https://lmv.math.cnrs.fr/equipes/cryptologie/' target='_blank'>Crypto</a>.
      Je travaillais précédemment à 
      <a href='https://www.uclouvain.be/' target='_blank'>l'UCLouvain</a>
      en Belgique dans l'équipe 
      <a href='https://www-crypto.elen.ucl.ac.be/crypto/default/home' target='_blank'>Crypto</a>.
      J'ai obtenu mon doctorat de
      <a href='https://www.sorbonne-universite.fr/' target='_blank'>Sorbonne Université</a>
      en 2018, effectué à 
      <a href='http://www.inria.fr/' target='_blank'>Inria</a>
      au sein de l'équipe-projet 
      <a href='https://www.rocq.inria.fr/secret/index.php?lg=en' target='_blank'>SECRET</a>
      sous la supervision d' 
      <a href='https://who.rocq.inria.fr/Anne.Canteaut' target='_blank'>Anne CANTEAUT</a>
      et de 
      <a href='https://who.rocq.inria.fr/Gaetan.Leurent' target='_blank'>Gaëtan LEURENT</a>.
      <br>
      L'objectif de mes recherche est de concilier les avancées de la cryptographie symétrique et de la résistance aux attaques par canaux auxiliaires, afin de construire des solutions cryptographiques résistantes aux attaques classiques et aux attaques sur les implémentations, à un coût adapté à l'internet des objets.
      <br>
      Mes centres d'intérêts comprennent<br>
      <ul lang='fr' type='circle'>
        <li>la conception d'algorithmes de cryptographie symétrique (chiffrements, MACs et chiffrements authentifiés),</li>
        <li>leur analyse statistique,</li>
        <li> l'implémentation de composants ou de primitives cryptographiques complètes (boîtes-S, matrices de diffusion, arithmétique dans les corps finis Booléens) en termes de circuits logiques et jusqu'à des implémentations  sur micro-contrôleurs,</li>
        <li>les contre-mesures aux attaques par canaux auxiliaires et attaques par fautes.</li>
      </ul>
      <p lang='fr'>
      Mon sujet de recherche principal est la combinaison de tous ces domaines. 
      <br>
      J'ai enseigné pendant trois ans à Sorbonne Université, au campus Pierre-et-Marie-Curie, à des étudiants de licence d'informatique, puis pendant deux ans à des étudiants de master d'électricité à l'UCLouvain, et actuellement à des étudiants de licence d'informatique à l'Université de Versailles.
      </p>"

# Experiences
author_work_experiences:
            - company_name: Université de Versailles
              company_logo: logo-lmv-2020.jpeg
              company_url: https://lmv.math.cnrs.fr/
              designation: Post-doctoral researcher
              designation_fr: Chercheur post-doctorant
              description: Designing cryptographic solutions for the IoT
              description_fr: Conception de solution cryptographiques pour les objets connectés
              visibility: true
            - company_name: Université Catholique de Louvain
              company_logo: logo_UCLouvain.jpeg
              company_url: https://uclouvain.be/fr/index.html
              designation: Post-doctoral researcher
              designation_fr: Chercheur post-doctorant
              description: Design of authenticated encryption schemes & Study of leakage evaluation strategies
              description_fr: Conception de schémas de chiffrement authentifié & étude des stratégies d'évaluation des fuites
              visibility: true
            - company_name: Inria
              company_logo: logo_inria.jpeg
              company_url: https://www.inria.fr/en
              designation: PhD student
              designation_fr: Doctorant
              description: Design of cryptographic solutions for lightweight security
              description_fr: Conception de solutions cryptographiques pour la sécurité à bas coût
              visibility: true

# Education
author_education_details:
              - college_logo: UPMC_Sorbonne_Universites.jpeg
                college_name: UPMC - Sorbonne Universités
                college_url: https://www.sorbonne-universite.fr/
                college_degree: PhD in Cryptography
                college_degree_fr: Doctorat en Cryptographie
                description: Constructions for Lightweight Cryptography
                description_fr: Constructions pour la cryptographie à bas coût
                visibility: true
              - college_logo: Logo_telecom.jpeg
                college_name: Télécom ParisTech
                college_url: https://www.telecom-paris.fr/
                college_degree: Ingénieur of Télécom ParisTech
                college_degree_fr: Ingénieur de Télécom ParisTech
                description: Masters with majors in Cryptography & Operations Research
                description_fr: majeures en Cryptographie & Recherche opérationnelle
                visibility: true
              - college_logo: logo_uvsq.jpeg
                college_name: Université de Versailles
                college_url: https://www.uvsq.fr/
                college_degree: Bachelor in Mathematics & Bachelor in Computer Science
                college_degree_fr: Licence en Mathématiques & Licence en Informatique
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: spook.jpeg
                project_title: Spook
                project_description: Sponge-Based Leakage-Resistant Authenticated Encryption
                project_description_fr: Chiffrement authentifié résistant aux fuites basé sur les Éponges
                project_url: https://www.spook.dev/
                visibility: true
              - project_thumbnail: saturnin.jpeg
                project_title: Saturnin
                project_description: A suite of lightweight symmetric algorithms for post-quantum security
                project_description_fr: Une gamme d'algorithmes symétriques à bas coût pour la sécurité post-quantique
                project_url: https://project.inria.fr/saturnin/
                visibility: true
              - project_thumbnail: reassure.jpeg
                project_title: Reassure
                project_description: Robust and Efficient Approaches to Evaluating Side Channel and Fault Attack Resilience
                project_description_fr: Approches robustes et efficaces pour l'évaluation de la résilience aux attaques par canaux auxiliaires et fautes
                project_url: https://reassure.eu/
                visibility: true
              - project_thumbnail: anr-logo.jpeg
                project_title: ANR BLOC
                project_description: Design ans analysis of block ciphers
                project_description_fr: Conception et analyse de chiffrements par blocs
                project_url: https://anr.fr/Project-ANR-11-INSE-0011
                visibility: true
              - project_thumbnail: anr-logo.jpeg
                project_title: ANR BRUTUS
                project_description: Authenticated encryption resistant to side channel attacks – BRUTUS
                project_description_fr: Chiffrements authentifiés et résistants aux attaques par canaux auxiliaires – BRUTUS
                project_url: https://anr.fr/Project-ANR-14-CE28-0015
                visibility: true

# social links
#twitter_username: johndoe
github_username:  seduval
#facebook_username: johndoe
linkedin_username: sebastien-duval-43110288
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe
dblp_username: 08/4501
rg_username: Sebastien_Duval
orcid: 0000-0003-2558-1756
scholar_username: pe5OBKYAAAAJ

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
#hyvor_talk_website_id: 476

# wakatime username (coding activity)
#wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
#formspree_email: johndoe@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/research/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /research/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
